import json
import os


def generate_analysis_notebook(
    results_dir: str,
    summary: dict,
    history_csv_path: str,
    summary_json_path: str,
):
    nb_path = os.path.join(results_dir, "analysis.ipynb")

    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Análisis de entrenamiento distribuido CIFAR-100\n",
                    "\n",
                    "Notebook generado automáticamente.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Resumen del experimento\n",
                    "\n",
                    f"- Dataset: {summary['dataset']}\n",
                    f"- Workers: {summary['workers']}\n",
                    f"- Rounds: {summary['rounds']}\n",
                    f"- Local epochs: {summary['local_epochs']}\n",
                    f"- Batch size: {summary['batch_size']}\n",
                    f"- Eval batch size: {summary['eval_batch_size']}\n",
                    f"- Learning rate: {summary['lr']}\n",
                    f"- Weight decay: {summary['weight_decay']}\n",
                    f"- Optimizer: {summary['optimizer']}\n",
                    f"- Momentum: {summary['momentum']}\n",
                    f"- Activation: {summary['activation']}\n",
                    f"- Negative slope: {summary['negative_slope']}\n",
                    f"- Dropout: {summary['dropout']}\n",
                    f"- Channels: {summary['channels']}\n",
                    f"- FC dim: {summary['fc_dim']}\n",
                    f"- Seed: {summary['seed']}\n",
                    f"- Augmentation: {summary['augmentation']}\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import json\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    "from pathlib import Path\n",
                    "\n",
                    f'csv_file = Path(r"{history_csv_path}")\n',
                    f'json_file = Path(r"{summary_json_path}")\n',
                    "\n",
                    "df = pd.read_csv(csv_file)\n",
                    "with open(json_file, 'r', encoding='utf-8') as f:\n",
                    "    summary = json.load(f)\n",
                    "\n",
                    "df.head()\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## Historial completo\n"],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": ["df\n"],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## Curvas principales\n"],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "plt.figure(figsize=(8,5))\n",
                    "plt.plot(df['round'], df['train_loss'], marker='o', label='Train Loss')\n",
                    "plt.plot(df['round'], df['test_loss'], marker='s', label='Test Loss')\n",
                    "plt.title('Loss por round')\n",
                    "plt.xlabel('Round')\n",
                    "plt.ylabel('Loss')\n",
                    "plt.grid(True)\n",
                    "plt.legend()\n",
                    "plt.show()\n",
                    "\n",
                    "plt.figure(figsize=(8,5))\n",
                    "plt.plot(df['round'], df['train_acc'], marker='o', label='Train Acc')\n",
                    "plt.plot(df['round'], df['test_acc'], marker='s', label='Test Acc')\n",
                    "plt.title('Accuracy por round')\n",
                    "plt.xlabel('Round')\n",
                    "plt.ylabel('Accuracy')\n",
                    "plt.grid(True)\n",
                    "plt.legend()\n",
                    "plt.show()\n",
                    "\n",
                    "plt.figure(figsize=(8,5))\n",
                    "plt.plot(df['round'], df['round_time'], marker='o')\n",
                    "plt.title('Tiempo por round')\n",
                    "plt.xlabel('Round')\n",
                    "plt.ylabel('Segundos')\n",
                    "plt.grid(True)\n",
                    "plt.show()\n",
                    "\n",
                    "plt.figure(figsize=(8,5))\n",
                    "plt.plot(df['round'], df['total_time'], marker='o')\n",
                    "plt.title('Tiempo acumulado')\n",
                    "plt.xlabel('Round')\n",
                    "plt.ylabel('Segundos')\n",
                    "plt.grid(True)\n",
                    "plt.show()\n",
                    "\n",
                    "plt.figure(figsize=(8,5))\n",
                    "plt.plot(df['round'], df['train_acc'] - df['test_acc'], marker='o')\n",
                    "plt.title('Gap Train-Test')\n",
                    "plt.xlabel('Round')\n",
                    "plt.ylabel('Gap')\n",
                    "plt.grid(True)\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## Resumen cargado\n"],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": ["summary\n"],
            },
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.x",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)

    print(f"  📓 Notebook generado: {nb_path}")